spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/platform
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true